spring:
  #  datasource:
  #    driver-class-name:
  #    url:
  #    username: root
  #    password:
  #      data: classpath:data-seeder.sql
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    org:
      springframework:
      hibernate:
        type:
          descriptor:
            sql: trace
